### ISSUE TITLE
"The Holy Torch" Pet Movement

### ISSUE THREAD

**Issue by coachl4d2** [PotatoPersonThing/CalValEX#15]
This pets movement is very glitchy and janky, is it possible to update the animation and movement so it moves more fluidly and smoothly?

**Comment by RamenGuy** [comment]
that'd likely require a resprite, which could happen but we dunno

**Comment by willowmaine** [comment]
I think they're referring to the actual movement of the pet in-game. What may be causing the janky movement could be the inertia being set too low, but that's just my guess.

**Comment by willowmaine** [comment]
Just checked it, seems that it doesn't use the newer pet template and has its own code for movement which is probably causing the problems. Someone could update it if they wanted to
