### ISSUE TITLE
MP Config Issue

### ISSUE THREAD

**Issue by TheBambino** [PotatoPersonThing/CalValEX#7]
The config can be modified & saved by all players in MP. Not just the admin.

**Comment by GinYuH** [comment]
the situation was discussed on the discord and it's known

**Comment by TheBambino** [comment]
Pretty sure this was the reason why It was brought up and it still hasn't been addressed. I assume it's going to be left as is?

**Comment by GinYuH** [comment]
it's in our plans to change it into having most configs locked to admins
